// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sistemaRH.Models;

#nullable disable

namespace sistemaRH.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221106151805_M001")]
    partial class M001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("sistemaRH.Models.Atividade", b =>
                {
                    b.Property<int>("IdAtividade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAtividade"), 1L, 1);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdValorHora")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.HasKey("IdAtividade");

                    b.HasIndex("IdValorHora");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("sistemaRH.Models.Trabalho", b =>
                {
                    b.Property<int>("IdTrabalho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTrabalho"), 1L, 1);

                    b.Property<int?>("IdAtividade")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdTrabalho");

                    b.HasIndex("IdAtividade");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Trabalhos");
                });

            modelBuilder.Entity("sistemaRH.Models.Usuario", b =>
                {
                    b.Property<int?>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdUsuario"), 1L, 1);

                    b.Property<string>("ConfirmaSenha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("sistemaRH.Models.ValorHora", b =>
                {
                    b.Property<int>("IdValorHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdValorHora"), 1L, 1);

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdValorHora");

                    b.ToTable("ValorHoras");
                });

            modelBuilder.Entity("sistemaRH.Models.Atividade", b =>
                {
                    b.HasOne("sistemaRH.Models.ValorHora", "ValorHora")
                        .WithMany("Atividade")
                        .HasForeignKey("IdValorHora");

                    b.Navigation("ValorHora");
                });

            modelBuilder.Entity("sistemaRH.Models.Trabalho", b =>
                {
                    b.HasOne("sistemaRH.Models.Atividade", "Atividade")
                        .WithMany("Trabalho")
                        .HasForeignKey("IdAtividade");

                    b.HasOne("sistemaRH.Models.Usuario", "Usuario")
                        .WithMany("Trabalho")
                        .HasForeignKey("IdUsuario");

                    b.Navigation("Atividade");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("sistemaRH.Models.Atividade", b =>
                {
                    b.Navigation("Trabalho");
                });

            modelBuilder.Entity("sistemaRH.Models.Usuario", b =>
                {
                    b.Navigation("Trabalho");
                });

            modelBuilder.Entity("sistemaRH.Models.ValorHora", b =>
                {
                    b.Navigation("Atividade");
                });
#pragma warning restore 612, 618
        }
    }
}
