// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sistemaRH.Models;

#nullable disable

namespace sistemaRH.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("sistemaRH.Models.Trabalho", b =>
                {
                    b.Property<int>("IdTrabalho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTrabalho"), 1L, 1);

                    b.Property<string>("DescTrabalho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cpf_usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdTrabalho");

                    b.HasIndex("cpf_usuario");

                    b.ToTable("Trabalhos");
                });

            modelBuilder.Entity("sistemaRH.Models.Usuario", b =>
                {
                    b.Property<string>("cpf_usuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConfirmaSenha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cpf_usuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("sistemaRH.Models.Trabalho", b =>
                {
                    b.HasOne("sistemaRH.Models.Usuario", "Usuario")
                        .WithMany("Trabalho")
                        .HasForeignKey("cpf_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("sistemaRH.Models.Usuario", b =>
                {
                    b.Navigation("Trabalho");
                });
#pragma warning restore 612, 618
        }
    }
}
